AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for ktask

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  crudapi:
    Type: AWS::Serverless::Function
    Properties: 
      PackageType: Image
      Events:
        Read:
          Type: Api
          Properties:
            Path: /todo
            Method: get

        ReadByStatus:
          Type: Api
          Properties:
            Path: /get_by_status
            Method: get

        ReadByOwner:
          Type: Api
          Properties:
            Path: /get_by_owner
            Method: get

        Create:
          Type: Api
          Properties:
            Path: /todo
            Method: post
        Update:
          Type: Api
          Properties:
            Path: /todo
            Method: put
        Delete:
          Type: Api
          Properties:
            Path: /todo
            Method: delete

        # Create todo TodoList
        GetTodoList:
          Type: Api
          Properties:
            Path: /todolist
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./crudapi
      DockerTag: todocrud

#  user:
#    Type: AWS::Serverless::Function
#    Properties:
#      PackageType: Image
#      Events:

#
#
#    Metadata:
#      Dockerfile: Dockerfile
#      DockerContext: ./user
#      DockerTag: user
