import boto3

#username = 'Alexandre'
#new_password = '#Jej1234'
#accesstoken = 'eyJraWQiOiJRQloxNktLcHhXaUpUb0ZZa1pnSENUUjlOUTFIRFc5NU9BTmNcLytxU1Blbz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIwOWEyYTk1NS1iZDEwLTRiN2YtOGFlMi04MThiZDA4ZGNhNjYiLCJldmVudF9pZCI6Ijg2ZmRmMDM2LTc0ZWEtNGZlYy05MDM0LTNkOWViZGIwMzIzNSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2MTg1MjEyNDEsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5zYS1lYXN0LTEuYW1hem9uYXdzLmNvbVwvc2EtZWFzdC0xX1I2RkV4WEQzciIsImV4cCI6MTYxODUyNDg0MSwiaWF0IjoxNjE4NTIxMjQxLCJqdGkiOiI1OWIyOGE0MC02ZTg3LTQyNTAtYjRiMi0zM2I4ZjgxODUyODciLCJjbGllbnRfaWQiOiJ2am1hdmZyb3A5MjdwZm5rOWpuMTVoMmZ0IiwidXNlcm5hbWUiOiJhbGV4YW5kcmUifQ.Ou6-K-UJjFSjAQ3s_KKbkGaNnwaNkIWMg-gULXF6l6PoC7J9JRH2oIzouB6nrD6v6EYvNqFyZKGBYZPWc-cjc_CUqDOWn4BcySxk9drSdBEoE4jcnRKW1XSZ6ThKpFqDzdva9Yd-J8SxyYLH1bJUOjnNRohOpNRJTWkpLCqGGgR0vgBn03tI15AQU0BjdEbZzj2BhFPpjTtRoppJIQ-Hpd9KCnGYGap22JX438ZuMJWIl8LLCCtm0KMJYd3GgI07NGK-WGmzbQkFVVNia74FfMmm5N4Gaovuo3Ftu5nD7Du6wzBv43vh0TweGkTQ4zY-Hsw5fVIhN5I97fEEpEcZIg'
def Change_password(username,new_password,accesstoken):
    client = boto3.client('cognito-idp', region_name='sa-east-1')

    response = client.change_password(PreviousPassword=new_password, ProposedPassword=new_password, AccessToken=accesstoken)

    return response