AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for cognito-openid

Globals:
  Function:
    Timeout: 15

Resources:
  CognitoFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        Authorization:
          Type: Api
          Properties:
            Path: /cognito
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./cognito
      DockerTag: python3.8-v1
